### ISSUE TITLE
JOSS paper comments

### ISSUE THREAD

**Issue by sskutnik** [ezsolti/feign#7]
## Figure 1 caption

Would be useful to indicate the detector location (upper right corner) within the caption for Figure 1. This is in the text, but it'd be helpful to be within the caption as well.

## Determining relative efficiency from pin center vs. random points

Specifically with respect to this text:
> Fig. \ref{fig:geomeff} illustrates one case when the source locations are the center of the pins and another case when ten source locations were randomly selected in each pin. One can see that the pin center approximation has a lower efficiency as compared to the case with randomly selected source locations inside the pin. **This is due to that the pin center case overestimates the traveled distances (thus underestimate the geometric efficiency).**

1. Why only select ten source locations for this evaluation?
2. How does the pin center over-estimate the traveled distance? If anything, it seems like this would be the mean value for the distribution of points throughout the pin. (i.e., as the pin is a circle, if we assume emissions are uniform throughout the pin, the integral probability for 0 < theta < pi is equal to that of pi < theta < 2 pi). Is there any way to recover any data on the distribution of points within the pin used for sampling (or to simply sample more points)?
3. I might suggest some minor rephrasing for clarity, such as:
> This is due to the fact that assuming all emissions originate from the center of the pin overestimates the traveled distances (thus underestimating the geometric efficiency).

## References

- Reference 1 (``@elterMVA``) needs a DOI / locatable citation. Based on the BibTeX, I'd suggest maybe using the ``@inproceedings`` tag instead of ``@conference``; that should then render the conference title.
- Reference 3 (``@pget``) is the same; recommend using ``@inproceedings`` in order to render the title; please provide a URL or DOI if available.
- Reference 4 (``Janssonthesis``) provide a URL to the online document or DOI if feasible.

## Miscellaneous (non-blocking)

1. I might suggest saying "MCNP syntax" (or especially, "MCNP convention") instead of "MCNP jargon"
2. The term "geometric efficiency" is a bit confusing given the more typical use to mean "solid angle subtended by the detector." I can see the validity of the use of this phrase here, but it may be useful to explicitly clarify that this is referring to the unattenuated contribution to a point detector.

**Comment by ezsolti** [comment]
@sskutnik : Thank you very much for the great comments. I modified the paper and the references based on your remarks. I have got a better reference for the PGET now. Regarding elterMVA, unfortunately the conference organizers still haven't put much effort into publishing the proceedings, so i cannot improve the citation to that one further. Shall I skip it? (Also, I still haven't mananged to render it correctly, maybe the Zs. messes things up, though I tried that also in various ways:))

Regarding your comment on the term "geometric efficiency". Would you propose to change the title as well? I actually had a dilemma about this term, whether I should go with it, or use something else. This one felt a bit more "obvious" for someone working with gamma spectroscopy, even if in this work only the unattenuated contribution is meant.

Related to the technical questions:

## Pin center vs random location

1, I selected only ten points because the pin diameter is reasonably small, and ten points seemed to sample the area well. Seemed to means here that I looked into how the mean curve converges with the number of random source sites, and it got converged already with ten points for the given geometry. Nevertheless, I thought this reasoning is slightly out of the scope of the paper. Do you think I should mention it?

2, Yes, the source locations are available in the [Experiment object](https://ezsolti.github.io/feign/experiment.html#feign.blocks.Experiment.sourcePoints). I have also felt it slightly counter-intuitive that the center case is not the same as the mean of the random locations, thus I have done an illustration for the simplest case. Let's consider only one pin (at (0,0), with radius 0.41cm), from which uncollided rays emitted from random locations are tracked to a detector point (at (170,170)). The random location is colored red when the distance traveled within the pin is less than the radius of the pin (which would be the center case), and blue when the distance traveled within the pin is greater than the radius. 

![detsourcedist_distribution](https://user-images.githubusercontent.com/11595297/64196601-7f676c00-ce84-11e9-9b4c-d4d976608ab9.png)

The figure illustrates that on average rays travel a shorter distance within the pin than the radius of the pin. The magnitude of this discrepancy of course depends on the detector location. Also the presence of neighboring pins complicate things further. The quoted conclusion is thus not a general one, nevertheless for a detector placed far and facing the corner, the statement is valid, the traveled distance is greater for a source in the pin center than the average of random source locations. Similarly as in 1, I felt that such an explanation would be unnecessary for the paper, but I would gladly include it, if you feel it improves the article.

(Btw, having the opportunity to show this figure feels like when one can show a backup slide during a presentation:) So I just hope that I actually answered what you asked for:))

**Comment by sskutnik** [comment]
Hi @ezsolti, I think this does a great job of answering my question, thank you. The references look good; they are sufficiently specific as to be locatable (even if ANS conference proceedings aren't always as accessible as one would ideally like). I think the changes here are sufficient.

My personal feelings toward the figure would be toward including it in the paper if practical, if only because it supports what is a nominally counter-intuitive point about the relative attenuation factor; your explanation makes a good deal of sense, and I realize that this has to do with the nature of the point-detector problem now that I see your figure. (i.e., I think a ring detector or isotropic series of point detectors would not manifest this bias, but a point detector does. Since the application is for point detectors, I actually think this finding is fairly important to emphasize as to why the geometry calculation you've made is superior to using the center-pin approximation.) Basically, I think it only helps to support the case for why this software is useful.  (This may also be a good way to introduce the concept of the "experiment" object in your discussion of the software and how this is used.)

With respect to terminology, this is a tough one. In the reactor physics world, a similar concept is represented by the Dancoff Factor; this is not a precise analogy, but it's relatively similar. You might call it a "view factor" or even "effective attenuation length"; that said, I also respect the fact that this works much like geometric efficiency in gamma spectroscopy, so this is an issue I am willing to defer to the author's judgment on.
